Checks: '*,-google-*'
WarningsAsErrors: ''
HeaderFilterRegex: ''
AnalyzeTemporaryDtors: true
CheckOptions:
  - key: readability-identifier-naming.NamespaceCase
    value: lower_case
  - key: readability-identifier-naming.VariableName
    value: lower_case
  - key: readability-identifier-naming.FunctionCase
    value: lower_case
